<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string|max:191',
            'password' => 'required|min:6|max:191|confirmed',
            'email' => 'required|max:191|email|unique:users,email,'.$this->route('user')
            // con .$this->route('user') se usa para que al momento de hacer update Forzar una regla unique para ignorar un ID
        ];
    }

    public function response(array $errors)
    {
        toast('¡Datos erroneos o no validdos!', 'error','top');
        return parent::response($errors); // TODO: Change the autogenerated stub
    }
}
